### ISSUE TITLE
New values for cloud data access

### ISSUE THREAD

**Issue by amilan17** [OSGeo/Cat-Interop#30]
- Google:BigQuery; https://cloud.google.com/bigquery/ ; Google Big Query
- AWS:S3; https://aws.amazon.com/documentation/s3/ ; Amazon Simple Storage Service 
- Google:GCS; https://cloud.google.com/storage/ ; Google Cloud Storage

**Comment by smrgeoinfo** [comment]
@amilan17 are you proposing adding these to the link properties lookup csv?

**Comment by dneufeldcu** [comment]
Looks like some good additions!

**Comment by dneufeldcu** [comment]
@amilan17 @smrgeoinfo @kwilcox @mloskot @hobu 

Let's move forward with a pull request with the additions if there are no objections?

**Comment by smrgeoinfo** [comment]
@amilan17 --can you create a pull request with the updates?

**Comment by amilan17** [comment]
K. thinks it's ready. https://github.com/OSGeo/Cat-Interop/pulls

**Comment by dneufeldcu** [comment]
Hello, Please merge the pull request. Thanks! Dave

https://github.com/OSGeo/Cat-Interop/pull/32#pullrequestreview-121849089
