### ISSUE TITLE
LinkPropertyLookupTable.csv

### ISSUE THREAD

**Issue by steingod** [OSGeo/Cat-Interop#33]
Would it be possible to have this in machine readable form, e.g. SKOS?

**Comment by tomkralidis** [comment]
@steingod thanks for the report.  First pass implemented in master and can be generated with:

```bash
 python export/export.py $VERSION $VERSION_DATE LinkPropertyLookupTable.csv skos
```
Does this work for you?  If the SKOS has issues, can you provide an example representation?  Thanks
