### ISSUE TITLE
add osgeo:tms and xyz?

### ISSUE THREAD

**Issue by pvgenuchten** [OSGeo/Cat-Interop#42]
osgeo:tms is mentioned but not included in the list
should we add a xyz tile protocol as commonly used for background imagery and vector tiles?

**Comment by smrgeoinfo** [comment]
yes

**Comment by tomkralidis** [comment]
+1

**Comment by pvgenuchten** [comment]
there seem no formal authority for xyz, suggestion here is to use osm as an authority, wikipedia includes them as a first mentioner of xyz, https://en.wikipedia.org/wiki/Tiled_web_map
alternative would be something at google, but couldn't find a proper reference, suggestions?
